import './globals.css'
import Providers from './src/components/Providers'
import Navbar from './src/components/layout/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" className="bg-white text-slate-900  antialiased">
      <body className="min-h-screen bg-slate-50 antialiased dark:bg-slate-900">
        <Providers>
          {/* ts-expect-error Server Component */}
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
