import './globals.css'
import Providers from './src/components/Providers'
import Footer from './src/components/layout/Footer'
import Navbar from './src/components/layout/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" className="bg-white text-slate-900  antialiased">
      <body className="flex min-h-screen flex-col bg-slate-50 antialiased dark:bg-slate-900">
        <Providers>
          <Navbar />
          <main className="flex-1 pt-20">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
