export const developers = [
  {
    id: 1,
    name: 'Vaibhav Sompura',
    email: 'vsompura3@gmail.com',
    age: 23,
    role: 'Frontend Developer',
    domain: 'Full-Stack Development',
    avatar: 'https://avatars.githubusercontent.com/u/42895093?v=4',
    linkedin_url: 'https://www.linkedin.com/in/vaibhav-sompura/',
    github_url: 'https://github.com/vsompura3',
  },
  {
    id: 2,
    name: 'Tanupam Saha',
    email: 'vsompura3@gmail.com',
    age: 23,
    role: 'Frontend Developer',
    domain: 'Full-Stack Development',
    avatar: 'https://avatars.githubusercontent.com/u/54593072?v=4',
    linkedin_url: 'https://www.linkedin.com/in/tanupamsaha/',
    github_url: 'https://github.com/decoder-17',
  },
  {
    id: 3,
    name: 'Neeraj Kumar',
    email: 'vsompura3@gmail.com',
    age: 23,
    role: 'Backend Developer',
    domain: 'Full-Stack Development',
    avatar: 'https://avatars.githubusercontent.com/u/55330971?v=4',
    linkedin_url: 'https://www.linkedin.com/in/neeraj-kumar-5178281b0',
    github_url: 'https://github.com/Ryuk-me',
  },
  {
    id: 4,
    name: 'Shivam Jaiswal',
    email: 'vsompura3@gmail.com',
    age: 21,
    role: 'Documentation',
    domain: 'Data Science',
    avatar: 'https://avatars.githubusercontent.com/u/113243195?v=4',
    linkedin_url: 'https://www.linkedin.com/in/vaibhav-sompura/',
    github_url: 'https://github.com/shivamjaiswal08',
  },
]
